### ISSUE TITLE
Would it be possible to support SharedWorkers?

### ISSUE THREAD

**Issue by okikio** [vdesjs/vite-plugin-monaco-editor#16]
Monaco uses up a lot of memory, so, I prefer to put workers in `SharedWorkers`. For the [astro](https://astro.build) [playground](https://astro.build/play), I used `SharedWorkers` to limit memory usage and ensure that multiple monaco editors can still work properly, you check out how I used it here https://github.com/snowpackjs/astro-repl/blob/741460dfcbe894473f8e66153926cc653d0fe8b9/src/editor/modules/monaco.ts#L258 

Would it be possible to support SharedWorkers?

**Comment by china-bin** [comment]
You can try to use the use the customWorkers options to specified absolute path:
```js
 monacoEditorPlugin({
            customWorkers: [
                {
                    label: "share",
                    entry: path.resolve(__dirname, "src/worker/share.worker")
                }
            ]
        })
```

**Comment by okikio** [comment]
Does the customWorkers options support doing this, `new SharedWorker(/* ... */)` in order to create custom workers?

**Comment by okikio** [comment]
Thank you, I truly appreciate it. You might want to add to the readme that you can use SharedWorkers.

**Comment by china-bin** [comment]
The `new SharedWorker(/* ... */)` should be write into the file `src/worker/share.worker`
