### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zlyyyy** [vdesjs/vite-plugin-monaco-editor#17]
/node_modules/vite-plugin-monaco-editor/dist/index.js:94
                    throw err;
                    ^

[Error: EEXIST: file already exists, mkdir '../dist/monacoeditorwork'] {
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '../dist/monacoeditorwork'
}

npm run build error

**Comment by zlyyyy** [comment]
#18

**Comment by china-bin** [comment]
Thanks for you pull request. The version v1.0.9 has update your fix!
