### ISSUE TITLE
404 editor.worker.bundle.js this path is error

### ISSUE THREAD

**Issue by SignDawn** [vdesjs/vite-plugin-monaco-editor#19]
why this path is error 404 ?
this path equals [current path]/monacoeditorwork/editor.worker.bundle.js

**Comment by SignDawn** [comment]
It is in /a one path use，It could 。
but it is in /a/b more path use ，It will error 404，result path is /a/monacoeditorwork/editor.worker.bundle.js

**Comment by china-bin** [comment]
The publicPath option to set `a/monacoeditorwork`,  In my enviroment that was no problme. My operate system is `windows10`

**Comment by SignDawn** [comment]
It may not apply，In some pages ，I use this component，for example：/workspace， /workspace/aa， /workspace/aa/bb，It is not a universal solution.
Chinese：它可能不适用，我在多个页面使用到了这个组件，例如说： /workspace，/workspace/aa，/workspace/aa/bb 路由，这不是一个通用的解决方案

**Comment by china-bin** [comment]
我大概明白你的意思了，等我有空我写个多页面的例子。你最好能给我提供一个多页面使用这个组件的仓库地址。或者提供一些具体的报错或者浏览器网页的404的请求地址。

**Comment by SignDawn** [comment]
@china-bin 
我提交了一个测试的代码仓库，地址：https://github.com/SignDawn/test-project
测试方式可以查看 readme ；望查看，谢谢

**Comment by china-bin** [comment]
@SignDawn  版本`v1.0.10`已修复这个问题。 这个问题的解决是把workPath改为绝对地址。

**Comment by SignDawn** [comment]
@china-bin 
感谢作者！
作者有考虑出一个 vue3 版本的通用 monaco-editor 组件吗？类似于 https://www.npmjs.com/package/vue-monaco-editor

**Comment by china-bin** [comment]
> @china-bin 感谢作者！ 作者有考虑出一个 vue3 版本的通用 monaco-editor 组件吗？类似于 https://www.npmjs.com/package/vue-monaco-editor

你好，我暂时没有这个考虑，感觉做这个东西对我的意义不大。我个人使用monaco-editor的场景可能更需要对其进行定制，这样去封装一层vue感觉没啥必要性，还增加心智成本。当然站在组件化的角度这种东西还是很有必要的，最好可以考虑叫这种通用组件的作者去升级vue3版本。

**Comment by juanevp** [comment]
I just noticed that when I have a base path set this plugin won't load the workers.
Say I have:
```javascript
export default defineConfig(({mode}) => {
    return {
        base: '/a/',
        plugins: [
            react(),
            monacoEditorPlugin({
                languageWorkers: ['editorWorkerService', 'json'],
            }),
        ],
    };
});
```

The worker scripts will be correctly reported as generated at: 

```
/a/monacoeditorwork/editor.worker.bundle.js
/a/monacoeditorwork/json.worker.bundle.js
```

But when I load monaco the browser tries to load the scripts at http://localhost:3000/monacoeditorwork/editor.worker.bundle.js ignoring the base path.

I believe this might be a consequence of the change from the last release which made the worker paths absolute.
