### ISSUE TITLE
请问在微前端中作为子应用使用的时候，会出现无法加载worker的问题。单独使用的时候不会出现问题

### ISSUE THREAD

**Issue by jiaruifeng1** [vdesjs/vite-plugin-monaco-editor#29]
查下来好像是因为worker不能跨域，插件中支持另外引入worker的方案么， 或者有没有其它思路呀，闹心呀。。。

![image](https://user-images.githubusercontent.com/46318244/179222056-285b8b79-3bdc-412f-be54-52f5325224fd.png)

**Comment by NomadBin** [comment]
> 查下来好像是因为worker不能跨域，插件中支持另外引入worker的方案么， 或者有没有其它思路呀，闹心呀。。。
> 
> ![image](https://user-images.githubusercontent.com/46318244/179222056-285b8b79-3bdc-412f-be54-52f5325224fd.png)


你可以通过cdn的形式引入woker，因为importScripts是可以跨域的：https://github.com/vdesjs/vite-plugin-monaco-editor/blob/85ecb8421448c94bfd291f8422fd4ab9f6dab5c0/src/index.ts#L105。

**Comment by jiaruifeng1** [comment]
> 

十分感谢！！
