### ISSUE TITLE
Wrong path resolution in writeBundle hook

### ISSUE THREAD

**Issue by tarnishablec** [vdesjs/vite-plugin-monaco-editor#3]
when Vite config provide absolute paths in config.root and config.outDir 
path will be resolved incorrectly

https://github.com/vdesjs/vite-plugin-monaco-editor/blob/0b362358b55fe7d69fba602b9c2ef80dbfa903d2/src/index.ts#L111
https://github.com/vdesjs/vite-plugin-monaco-editor/blob/0b362358b55fe7d69fba602b9c2ef80dbfa903d2/src/index.ts#L127-L134

**Comment by china-bin** [comment]
I've tested it on the window. The `path.posix.resolve` seem not support window. I will replace `path.posix.resolve` to the `path.resolve` 
ps: The path.resolve should be  cross-platform

**Comment by china-bin** [comment]
Already release version v1.0.3. Thank for your contribution!

**Comment by tarnishablec** [comment]
#4 fixed
