### ISSUE TITLE
Error: ENOENT: no such file or directory, stat 'node_modules/.monaco/'

### ISSUE THREAD

**Issue by ackzell** [vdesjs/vite-plugin-monaco-editor#5]
I don't know what is wrong. I followed the readme instructions and this is what I get when trying to `npm run dev` on my vite project.

I'm using WSL  2 
Node version: 16.7.0
monaco-editor@0.26.1

Could you help me fix it?

```> vite

error when starting dev server:
Error: ENOENT: no such file or directory, stat 'node_modules/.monaco/'
    at Object.statSync (node:fs:1536:3)
    at __node_internal_ (node:internal/fs/utils:793:8)
    at Object.rmdirSync (node:fs:1156:15)```

**Comment by china-bin** [comment]
You can do the following step:
```bash
1. git clone https://github.com/vdesjs/vite-plugin-monaco-editor.git
2. cd vite-plugin-monaco-editor 
3. yarn
4. npm run test:dev
```

If  the above setps are successful, I think the problem should be fixed
