### ISSUE TITLE
Support CDN?

### ISSUE THREAD

**Issue by gadzan** [vdesjs/vite-plugin-monaco-editor#8]
Any plan to support CDN?

**Comment by china-bin** [comment]
The v1.0.5 has suppport cdn.

**Comment by gadzan** [comment]
Wow Great! Thanks🥳

**Comment by gadzan** [comment]
> The v1.0.5 has suppport cdn.
> 
> vite.config.js
> 
> ```js
> plugins: [
>  monacoEditorPlugin({
>             publicPath: 'https://unpkg.com/vite-plugin-monaco-editor@1.0.5/cdn'
>         })
> ]
> ```

如果设置了CDN，打包后就不会产生`worker.bundle.js`文件...怎么办？

**Comment by agileago** [comment]
@china-bin 设置了cdn，打包就不会生成worker,然后就上传不到cdn....
